
import React, { useEffect, useMemo, useState } from "react";
import "./creator.css";

const API = "/api/cafes";
const DRINK = ["Taste","Aroma","Body / texture","Temperature","Balance"];
const PASTRY = ["Flavour","Texture","Freshness","Filling","Presentation"];

function avg(values){const n=values.map(Number).filter(v=>Number.isFinite(v)&&v>0);return n.length?n.reduce((a,b)=>a+b,0)/n.length:0}
function score(c){const d=avg(Object.values(c?.drink?.ratings||{}));const p=avg(Object.values(c?.pastry?.ratings||{}));const s=avg([c?.atmosphere,c?.service,c?.value]);const hero=avg([d,p].filter(Boolean));const total=hero&&s?hero*.72+s*.28:hero||s||0;return total?Math.round(total*20):0}
function emptyCafe(){return {id:Date.now(),name:"New café",city:"Copenhagen",country:"Denmark",visitedOn:new Date().toISOString().slice(0,10),scene:"",imgs:[],drink:{type:"",mod:"",price:0,note:"",ratings:Object.fromEntries(DRINK.map(x=>[x,0]))},pastry:{type:"",subtype:"",price:0,note:"",ratings:Object.fromEntries(PASTRY.map(x=>[x,0]))},atmosphere:0,service:0,value:0,bestFor:[],take:"",reason:""}}
function mark(){return <div className="creator-mark">F</div>}
function ratingRows(labels, group, cafe, update){return <div className="creator-ratings">{labels.map(label=><label key={label}><span>{label}</span><input type="range" min="0" max="5" step=".5" value={cafe[group]?.ratings?.[label]||0} onChange={e=>update(group,label,Number(e.target.value))}/><b>{(cafe[group]?.ratings?.[label]||0).toFixed(1)}</b></label>)}</div>}
function sceneRating(label,value,onChange){return <label><span>{label}</span><input type="range" min="0" max="5" step=".5" value={value||0} onChange={e=>onChange(Number(e.target.value))}/><b>{(value||0).toFixed(1)}</b></label>}
function initials(name){return String(name||"Fika").split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase()}
function wrap(ctx,text,maxWidth,maxLines){const words=String(text||"").split(/\s+/);const lines=[];let line="";for(const w of words){const t=line?line+" "+w:w;if(ctx.measureText(t).width<=maxWidth||!line)line=t;else{lines.push(line);line=w;if(lines.length>=maxLines)break}}if(line&&lines.length<maxLines)lines.push(line);return lines}
async function imageBitmap(url){if(!url)return null;try{const r=await fetch(url);if(!r.ok)return null;return await createImageBitmap(await r.blob())}catch{return null}}
async function exportCard(cafe,kind){
  const sizes={story:[1080,1920],portrait:[1080,1350],square:[1080,1080]};
  const size=sizes[kind]||sizes.portrait;const canvas=document.createElement("canvas");canvas.width=size[0];canvas.height=size[1];const ctx=canvas.getContext("2d");const W=canvas.width,H=canvas.height,p=Math.round(W*.065),photoH=Math.round(H*(kind==="story"?.56:.52));
  ctx.fillStyle="#211c19";ctx.fillRect(0,0,W,H);
  const img=await imageBitmap(Array.isArray(cafe.imgs)?cafe.imgs[0]:cafe.imgs);
  if(img){const sr=img.width/img.height,tr=W/photoH;let sx=0,sy=0,sw=img.width,sh=img.height;if(sr>tr){sw=img.height*tr;sx=(img.width-sw)/2}else{sh=img.width/tr;sy=(img.height-sh)/2}ctx.drawImage(img,sx,sy,sw,sh,0,0,W,photoH);ctx.fillStyle="rgba(0,0,0,.2)";ctx.fillRect(0,0,W,photoH)}else{const g=ctx.createLinearGradient(0,0,W,photoH);g.addColorStop(0,"#d6a18a");g.addColorStop(1,"#b8c19d");ctx.fillStyle=g;ctx.fillRect(0,0,W,photoH);ctx.fillStyle="#211c19";ctx.font="italic 700 "+Math.round(W*.18)+"px Georgia";ctx.textAlign="center";ctx.fillText(initials(cafe.name),W/2,photoH/2);ctx.textAlign="left"}
  ctx.fillStyle="#fffdf9";ctx.font="700 "+Math.round(W*.027)+"px Arial";ctx.fillText("WORTH THE FIKA",p,p+35);
  const sc=score(cafe);ctx.fillStyle="#f5efe6";ctx.beginPath();ctx.arc(W-p-90,photoH-p-90,90,0,Math.PI*2);ctx.fill();ctx.fillStyle="#211c19";ctx.textAlign="center";ctx.font="500 70px Georgia";ctx.fillText(String(sc||"–"),W-p-90,photoH-p-78);ctx.font="700 18px Arial";ctx.fillStyle="#776e67";ctx.fillText("/100",W-p-90,photoH-p-48);ctx.textAlign="left";
  let y=photoH+Math.round(H*.07);ctx.fillStyle="#e9b8a7";ctx.font="700 24px Arial";ctx.fillText([cafe.city,cafe.country].filter(Boolean).join(" · ").toUpperCase(),p,y);y+=Math.round(H*.07);ctx.fillStyle="#f5efe6";ctx.font="500 "+Math.round(W*(kind==="story"?.085:.07))+"px Georgia";for(const line of wrap(ctx,cafe.name,W-p*2,2)){ctx.fillText(line,p,y);y+=Math.round(W*.08)}y+=25;ctx.fillStyle="#cec3ba";ctx.font="400 34px Arial";for(const line of wrap(ctx,cafe.take||cafe.reason||"A café worth remembering.",W-p*2,3)){ctx.fillText(line,p,y);y+=48}
  ctx.fillStyle="#e9b8a7";ctx.font="700 24px Arial";ctx.fillText("@WORTHTHEFIKA",p,H-p);
  const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/png",1));const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download=String(cafe.name||"fika").toLowerCase().replace(/[^a-z0-9]+/g,"-")+"-"+kind+".png";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500);
}
function caption(c){const tags=(c.bestFor||[]).slice(0,4).map(x=>"#"+String(x).replace(/[^a-z0-9]+/gi,"")).join(" ");return [c.name+" · "+(c.city||""),"Worth the Fika score: "+score(c)+"/100",c.take||c.reason||"",c.drink?.type?"☕ "+c.drink.type:"",c.pastry?.type?"🥐 "+c.pastry.type:"","",tags+" #WorthTheFika #Fika"].join("\n")}

export default function CreatorStudio(){
  const [cafes,setCafes]=useState([]),[selectedId,setSelectedId]=useState(null),[code,setCode]=useState(()=>sessionStorage.getItem("wtfika:admin")||""),[ready,setReady]=useState(false),[tab,setTab]=useState("review"),[status,setStatus]=useState(""),[uploading,setUploading]=useState(false);
  const selected=useMemo(()=>cafes.find(c=>String(c.id)===String(selectedId))||cafes[0],[cafes,selectedId]);
  useEffect(()=>{(async()=>{try{const r=await fetch(API);let data=r.ok?await r.json():[];if(!data.length)data=await fetch("/cafes.json").then(x=>x.json());setCafes(Array.isArray(data)?data:[]);setSelectedId(data?.[0]?.id||null)}catch{setCafes([])}})()},[]);
  useEffect(()=>{const saved=sessionStorage.getItem("wtfika:admin");if(saved)loginWith(saved,false)},[]);
  async function loginWith(value,show=true){setStatus("Checking…");try{const r=await fetch("/api/admin-check",{method:"POST",headers:{"x-admin-code":value}});if(!r.ok)throw 0;sessionStorage.setItem("wtfika:admin",value);setCode(value);setReady(true);setStatus("")}catch{sessionStorage.removeItem("wtfika:admin");setReady(false);setStatus(show?"Wrong admin code":"")}}
  function patch(field,value){setCafes(list=>list.map(c=>c.id===selected.id?{...c,[field]:value}:c))}
  function nested(group,field,value){setCafes(list=>list.map(c=>c.id===selected.id?{...c,[group]:{...(c[group]||{}),[field]:value}}:c))}
  function rate(group,label,value){setCafes(list=>list.map(c=>c.id===selected.id?{...c,[group]:{...(c[group]||{}),ratings:{...(c[group]?.ratings||{}),[label]:value}}}:c))}
  function add(){const c=emptyCafe();setCafes(list=>[c,...list]);setSelectedId(c.id);setTab("review");setStatus("New review ready")}
  async function publish(){setStatus("Publishing…");try{const r=await fetch(API,{method:"POST",headers:{"content-type":"application/json","x-admin-code":code},body:JSON.stringify({cafes})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"failed");setStatus("Published ✓");setTimeout(()=>setStatus(""),2500)}catch(e){setStatus(e.message==="unauthorized"?"Wrong admin code":"Publish failed")}}
  async function upload(e){const files=Array.from(e.target.files||[]).slice(0,6);e.target.value="";if(!files.length)return;setUploading(true);setStatus("Uploading photos…");const urls=[];try{for(const file of files){const f=new FormData();f.append("file",file);const r=await fetch("/api/images/upload",{method:"POST",headers:{"x-admin-code":code},body:f});const d=await r.json();if(!r.ok)throw new Error(d.error);urls.push(d.url)}patch("imgs",[...(selected.imgs||[]),...urls].slice(0,6));setStatus("Photos added · publish to save")}catch{setStatus("Photo upload failed")}finally{setUploading(false)}}
  if(!ready)return <main className="creator-login"><form onSubmit={e=>{e.preventDefault();loginWith(code,true)}}>{mark()}<p className="creator-eyebrow">Private creator studio</p><h1>Rate your next fika.</h1><p>Add cafés, upload your photos, score what you tasted and export Instagram cards.</p><input type="password" value={code} onChange={e=>setCode(e.target.value)} placeholder="Admin code" autoFocus/><button>Open creator studio</button>{status&&<small>{status}</small>}<a href="/">Back to public site</a></form></main>;
  if(!selected)return <main className="creator-empty">{mark()}<h1>No cafés yet.</h1><button onClick={add}>+ Add your first café</button></main>;
  const photos=Array.isArray(selected.imgs)?selected.imgs:[];
  return <main className="creator-shell">
    <header><div>{mark()}<div><span>CREATOR STUDIO</span><h1>Worth the Fika</h1></div></div><nav><small>{status}</small><a href="/">Public site</a><button onClick={()=>{sessionStorage.removeItem("wtfika:admin");setReady(false)}}>Log out</button><button className="creator-primary" onClick={publish}>Publish all</button></nav></header>
    <div className="creator-layout">
      <aside><button className="creator-new" onClick={add}>+ New fika review</button>{cafes.map(c=><button className={c.id===selected.id?"active":""} key={c.id} onClick={()=>{setSelectedId(c.id);setTab("review")}}><b>{c.name}</b><span>{c.city||"No city"} · {score(c)||"–"}/100</span></button>)}</aside>
      <section className="creator-content">
        <div className="creator-title"><div><span>{selected.visitedOn||"Draft review"}</span><h2>{selected.name}</h2></div><strong>{score(selected)||"–"}<small>/100</small></strong></div>
        <div className="creator-tabs"><button className={tab==="review"?"active":""} onClick={()=>setTab("review")}>1 · Review</button><button className={tab==="photos"?"active":""} onClick={()=>setTab("photos")}>2 · Photos ({photos.length})</button><button className={tab==="social"?"active":""} onClick={()=>setTab("social")}>3 · Instagram</button></div>
        {tab==="review"&&<div className="creator-card">
          <h3>Café details</h3><div className="creator-fields"><label>Name<input value={selected.name||""} onChange={e=>patch("name",e.target.value)}/></label><label>City<input value={selected.city||""} onChange={e=>patch("city",e.target.value)}/></label><label>Country<input value={selected.country||""} onChange={e=>patch("country",e.target.value)}/></label><label>Date visited<input type="date" value={selected.visitedOn||""} onChange={e=>patch("visitedOn",e.target.value)}/></label><label>Vibe<input value={selected.scene||""} onChange={e=>patch("scene",e.target.value)}/></label><label>Best for<input value={(selected.bestFor||[]).join(", ")} onChange={e=>patch("bestFor",e.target.value.split(",").map(x=>x.trim()).filter(Boolean))}/></label></div>
          <h3>Drink</h3><div className="creator-fields"><label>Drink<input value={selected.drink?.type||""} onChange={e=>nested("drink","type",e.target.value)}/></label><label>Detail<input value={selected.drink?.mod||""} onChange={e=>nested("drink","mod",e.target.value)}/></label><label>Price<input type="number" value={selected.drink?.price||0} onChange={e=>nested("drink","price",Number(e.target.value))}/></label><label className="wide">Tasting note<textarea value={selected.drink?.note||""} onChange={e=>nested("drink","note",e.target.value)}/></label></div>{ratingRows(DRINK,"drink",selected,rate)}
          <h3>Pastry</h3><div className="creator-fields"><label>Pastry<input value={selected.pastry?.type||""} onChange={e=>nested("pastry","type",e.target.value)}/></label><label>Detail<input value={selected.pastry?.subtype||""} onChange={e=>nested("pastry","subtype",e.target.value)}/></label><label>Price<input type="number" value={selected.pastry?.price||0} onChange={e=>nested("pastry","price",Number(e.target.value))}/></label><label className="wide">Tasting note<textarea value={selected.pastry?.note||""} onChange={e=>nested("pastry","note",e.target.value)}/></label></div>{ratingRows(PASTRY,"pastry",selected,rate)}
          <h3>Whole experience</h3><div className="creator-ratings">{sceneRating("Atmosphere",selected.atmosphere,v=>patch("atmosphere",v))}{sceneRating("Service",selected.service,v=>patch("service",v))}{sceneRating("Value",selected.value,v=>patch("value",v))}</div>
          <h3>Your verdict</h3><div className="creator-fields"><label className="wide">Short public take<textarea value={selected.take||""} onChange={e=>patch("take",e.target.value)}/></label><label className="wide">Why it is worth the fika<textarea value={selected.reason||""} onChange={e=>patch("reason",e.target.value)}/></label></div>
        </div>}
        {tab==="photos"&&<div className="creator-card"><h3>Upload from your phone</h3><p>The first photo is the public cover and Instagram image.</p><label className="creator-upload"><input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" multiple onChange={upload} disabled={uploading}/><b>{uploading?"Uploading…":"+ Add café photos"}</b><span>Up to 6 photos</span></label><div className="creator-photo-grid">{photos.map((url,i)=><figure key={url+i}><img src={url}/>{i===0&&<em>Cover</em>}<div>{i>0&&<button onClick={()=>{const a=[...photos];const one=a.splice(i,1)[0];a.unshift(one);patch("imgs",a)}}>Make cover</button>}<button onClick={()=>patch("imgs",photos.filter((_,x)=>x!==i))}>Remove</button></div></figure>)}</div></div>}
        {tab==="social"&&<div className="creator-card"><h3>Instagram card studio</h3><div className="creator-social-preview"><div>{photos[0]?<img src={photos[0]}/>:<span>{initials(selected.name)}</span>}</div><section><small>{selected.city}</small><h4>{selected.name}</h4><p>{selected.take||selected.reason||"Add your verdict in the Review tab."}</p><strong>{score(selected)||"–"}<small>/100</small></strong></section></div><div className="creator-export"><button onClick={()=>exportCard(selected,"story")}>Story <span>1080×1920</span></button><button onClick={()=>exportCard(selected,"portrait")}>Portrait <span>1080×1350</span></button><button onClick={()=>exportCard(selected,"square")}>Square <span>1080×1080</span></button></div><div className="creator-caption"><pre>{caption(selected)}</pre><button onClick={async()=>{await navigator.clipboard.writeText(caption(selected));setStatus("Caption copied ✓")}}>Copy caption</button></div></div>}
        <footer><span>Changes stay private until you publish.</span><div><button onClick={()=>setTab(tab==="review"?"photos":tab==="photos"?"social":"review")}>{tab==="review"?"Next: photos":tab==="photos"?"Next: Instagram":"Back to review"}</button><button className="creator-primary" onClick={publish}>Publish all</button></div></footer>
      </section>
    </div>
  </main>
}
