export const MILKS=['Regular milk','Whole milk','Semi-skimmed milk','Skimmed milk','Lactose-free milk','Oat milk','Soy milk','Almond milk','Coconut milk','Pea milk','No milk'];
export const DRINKS=['Espresso','Ristretto','Lungo','Americano','Long black','Cappuccino','Flat white','Caffè latte','Latte macchiato','Espresso macchiato','Cortado','Piccolo latte','Mocha','Filter Coffee','Pour-over / V60','Chemex','AeroPress','French press','Batch brew','Cold brew','Iced coffee','Iced latte','Iced americano','Affogato','Turkish coffee','Decaf coffee','Matcha','Matcha latte','Iced matcha latte','Chai latte','Dirty chai','Hojicha latte','Hot chocolate','Tea','Iced tea','Golden latte','Juice','Lemonade'];
export const PASTRIES=['Croissant','Pain au chocolat','Almond croissant','Cardamom Bun','Cinnamon bun','Danish pastry','Spandauer','Tebirkes','Kanelsnegl','Kardemommesnurre','Morning bun','Scone','Muffin','Cookie','Brownie','Carrot cake','Cheesecake','Chocolate cake','Lemon cake','Tart','Éclair','Choux pastry','Doughnut','Babka','Semla','Princess cake','Madeleine','Financier','Baklava','Pastel de nata','Sourdough toast'];
export const TAGS=['Cozy solo','Queer-friendly','Hidden gem','Date spot','Friends','Laptop work','Sunny terrace','Dog-friendly','Family-friendly','Great coffee','Fresh pastries','Vegan options'];
export function tagLabel(tag){if(/\p{Extended_Pictographic}/u.test(tag))return tag;const t=tag.toLowerCase();const emoji=/queer|lgbt|rainbow/.test(t)?'🌈':/solo|cozy/.test(t)?'🛋️':/hidden/.test(t)?'💎':/date/.test(t)?'💕':/^friends$/.test(t)?'🫶':/laptop|work/.test(t)?'💻':/sun|terrace|outdoor/.test(t)?'☀️':/dog/.test(t)?'🐾':/family|kid/.test(t)?'👨‍👩‍👧':/coffee/.test(t)?'☕':/pastr|bak/.test(t)?'🥐':/vegan|plant/.test(t)?'🌱':'✨';return emoji+' '+tag}
export function criterionLabel(label){const map={'Taste':'🤤','Flavour':'😋','Aroma':'🌸','Body':'☕️','Temperature':'🌡️','Balance':'⚖️','Texture':'🥐','Freshness':'🌿','Filling':'🍯','Presentation':'✨','Atmosphere':'🛋️','Service':'🫶','Value':'💰'};return (map[label]||'⭐')+' '+label}
export function foodEmoji(type,kind='drink'){const t=(type||'').toLowerCase();if(kind==='drink')return /matcha|hojicha|tea/.test(t)?'🍵':/chocolate|mocha/.test(t)?'🍫':/juice|lemon/.test(t)?'🍋':'☕';return /cake|tart/.test(t)?'🍰':/cookie/.test(t)?'🍪':/chocolate|brownie/.test(t)?'🍫':/doughnut/.test(t)?'🍩':'🥐'}
export function isCoffee(type){return Boolean(type)&&!/(matcha|hojicha|^tea$|iced tea|chocolate|golden|juice|lemonade|^chai latte$)/i.test(type)}
export function tastingMeta(c){return [c?.shots==='1'?'Single shot':c?.shots==='2'?'Double shot':c?.shots==='3'?'Triple shot':null,c?.temp,c?.milk,c?.mod,c?.subtype].filter(Boolean).join(' · ')}
export function ratingEmoji(label){return criterionLabel(label).split(' ')[0]}
export function reviewMonth(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value||''))return '';const d=new Date(value+'T12:00:00Z');return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('en',{month:'short',year:'numeric',timeZone:'UTC'}).format(d)}
export function priceLabel(value,country){const n=Number(value);return n>0?n.toLocaleString('en',{maximumFractionDigits:2})+(country==='Sweden'?' SEK':country==='Denmark'?' DKK':''):'Price not added'}

export function ratingEntries(category){return Object.entries(category?.ratings||{}).filter(([label])=>!/^clarity$|^body\s*\/\s*texture$/i.test(label.trim()))}
